# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FavoritenBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, benutzername: str=None, event_id: int=None):  # noqa: E501
        """FavoritenBody - a model defined in Swagger

        :param benutzername: The benutzername of this FavoritenBody.  # noqa: E501
        :type benutzername: str
        :param event_id: The event_id of this FavoritenBody.  # noqa: E501
        :type event_id: int
        """
        self.swagger_types = {
            'benutzername': str,
            'event_id': int
        }

        self.attribute_map = {
            'benutzername': 'benutzername',
            'event_id': 'event_id'
        }
        self._benutzername = benutzername
        self._event_id = event_id

    @classmethod
    def from_dict(cls, dikt) -> 'FavoritenBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The favoriten_body of this FavoritenBody.  # noqa: E501
        :rtype: FavoritenBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def benutzername(self) -> str:
        """Gets the benutzername of this FavoritenBody.


        :return: The benutzername of this FavoritenBody.
        :rtype: str
        """
        return self._benutzername

    @benutzername.setter
    def benutzername(self, benutzername: str):
        """Sets the benutzername of this FavoritenBody.


        :param benutzername: The benutzername of this FavoritenBody.
        :type benutzername: str
        """
        if benutzername is None:
            raise ValueError("Invalid value for `benutzername`, must not be `None`")  # noqa: E501

        self._benutzername = benutzername

    @property
    def event_id(self) -> int:
        """Gets the event_id of this FavoritenBody.


        :return: The event_id of this FavoritenBody.
        :rtype: int
        """
        return self._event_id

    @event_id.setter
    def event_id(self, event_id: int):
        """Sets the event_id of this FavoritenBody.


        :param event_id: The event_id of this FavoritenBody.
        :type event_id: int
        """
        if event_id is None:
            raise ValueError("Invalid value for `event_id`, must not be `None`")  # noqa: E501

        self._event_id = event_id
