# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, email: str=None, passwort: str=None):  # noqa: E501
        """UserBody - a model defined in Swagger

        :param benutzername: The benutzername of this UserBody.  # noqa: E501
        :type benutzername: str
        :param passwort: The passwort of this UserBody.  # noqa: E501
        :type passwort: str
        """
        self.swagger_types = {
            'email': str,
            'passwort': str
        }

        self.attribute_map = {
            'email': 'email',
            'passwort': 'passwort'
        }
        self._email = email
        self._passwort = passwort

    @classmethod
    def from_dict(cls, dikt) -> 'UserBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The user_body of this UserBody.  # noqa: E501
        :rtype: UserBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email(self) -> str:
        """Gets the benutzername of this UserBody.


        :return: The benutzername of this UserBody.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the benutzername of this UserBody.


        :param benutzername: The benutzername of this UserBody.
        :type benutzername: str
        """
        if email is None:
            raise ValueError("Invalid value for `benutzername`, must not be `None`")  # noqa: E501

        self._email = email
    
    @property
    def passwort(self) -> str:
        """Gets the passwort of this UserBody.


        :return: The passwort of this UserBody.
        :rtype: str
        """
        return self._passwort

    @passwort.setter
    def passwort(self, passwort: str):
        """Sets the passwort of this UserBody.


        :param passwort: The passwort of this UserBody.
        :type passwort: str
        """
        if passwort is None:
            raise ValueError("Invalid value for `passwort`, must not be `None`")  # noqa: E501

        self._passwort = passwort
