@startuml
package "Frontend" {
  [MainWindow.xaml]
  [MainWindow.xaml.cs]
  [Models]
  [Resources]
  [Services]
  package Pages {
    [LoginPage.xaml]
    [LoginPage.xaml.cs]
    [RegisterPage.xaml]
    [RegisterPage.xaml.cs]
    [MainPage.xaml]
    [MainPage.xaml.cs]
    [ExplorePage.xaml]
    [ExplorePage.xaml.cs]
    [ProfilePage.xaml]
    [ProfilePage.xaml.cs]
    [FavoritesPage.xaml]
    [FavoritesPage.xaml.cs]
    [MapPage.xaml]
    [MapPage.xaml.cs]
    [MoreInfoPage.xaml]
    [MoreInfoPage.xaml.cs]
  }
  package UserControls {
    [EventMiniViewUserControl]
  }
  package ViewModels {
    [MainViewModel.cs]
    [LoginViewModel.cs]
    [RegisterViewModel.cs]
    [ExploreViewModel.cs]
    [ProfileViewModel.cs]
    [FavoritesViewModel.cs]
    [MapViewModel.cs]
    [MoreInfoViewModel.cs]
  }
}

package "Backend" {
  [Swagger API]

  package swagger_server {
    package swagger {
      [swagger.yaml]
    }
    [controllers]
    [models]
    [utils]
  }

  package services {
    [event_fetcher.py]
  }


}

  [Supabase DB]
  [Externe API]

[MainWindow.xaml.cs] --> Pages
Pages --> UserControls
Pages --> ViewModels
Pages --> Services
Pages --> Models
Pages --> Resources

[MainWindow.xaml.cs] ..> [Swagger API] : REST-API

[Swagger API] --> swagger_server
swagger_server --> controllers
swagger_server --> models
swagger_server --> utils
controllers --> services
controllers --> [Supabase DB]
services --> [Externe API]


@enduml